{
 "title": "length histogram double line",
 "tags": [ "length histogram" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "readwrite",
    "label": "readwrite",
    "query": {
     "query": "label_values(pika_db_read_write_bucket, step)"
    }
   },
   {
    "name": "data_type",
    "label": "data_type",
    "query": {
     "query": "label_values(pika_db_read_write_bucket, dbtype)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "key $readwrite",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(histogram_quantile(0.5, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])),1)",
     "legendFormat": "P50"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])),1)",
     "legendFormat": "P90"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.99, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])),1)",
     "legendFormat": "P99"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])),1)",
     "legendFormat": "P999"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])),1)",
     "legendFormat": "P9999"
    },
    {
     "expr": "delta(pika_db_read_write_sum{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])/delta(pika_db_read_write_count{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])",
     "legendFormat": "AVG"
    },
    {
     "expr": "rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"key\"}[1m])",
     "legendFormat": "le{{le}}"
    }
   ]
  },
  {
   "title": "field $readwrite",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(histogram_quantile(0.5, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])),1)",
     "legendFormat": "P50"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])),1)",
     "legendFormat": "P90"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.99, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])),1)",
     "legendFormat": "P99"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])),1)",
     "legendFormat": "P999"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])),1)",
     "legendFormat": "P9999"
    },
    {
     "expr": "delta(pika_db_read_write_sum{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])/delta(pika_db_read_write_count{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])",
     "legendFormat": "AVG"
    },
    {
     "expr": "rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"field\"}[1m])",
     "legendFormat": "le{{le}}"
    }
   ]
  },
  {
   "title": "value $readwrite",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(histogram_quantile(0.5, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])),1)",
     "legendFormat": "P50"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])),1)",
     "legendFormat": "P90"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.99, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])),1)",
     "legendFormat": "P99"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])),1)",
     "legendFormat": "P999"
    },
    {
     "expr": "clamp_min(histogram_quantile(0.9999, rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])),1)",
     "legendFormat": "P9999"
    },
    {
     "expr": "delta(pika_db_read_write_sum{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])/delta(pika_db_read_write_count{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])",
     "legendFormat": "AVG"
    },
    {
     "expr": "rate(pika_db_read_write_bucket{dbtype=\"$data_type\",step=\"$readwrite\",field=\"value\"}[1m])",
     "legendFormat": "le{{le}}"
    }
   ]
  }
 ]
}