{
 "title": "properties cfstat",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "data_type",
    "label": "data_type",
    "query": "\"props-default\",\"props-system\",\"props-default_sk\",` "
   },
   {
    "name": "cfstats_actual",
    "label": "cfstats_actual",
    "query": "AvgSec,CompactedFiles,NumFiles,ReadMBps,Score,SizeBytes,WriteAmp,WriteMBps,"
   },
   {
    "name": "cfstats_rate",
    "label": "cfstats_rate",
    "query": "CompCount,CompMergeCPU,CompSec,KeyDrop,KeyIn,MovedGB,ReadGB,RnGB,Rnp1GB,WnewGB,WriteGB"
   },
   {
    "name": "io_stalls",
    "label": "io_stalls",
    "query": "level0_numfiles,level0_numfiles_with_compaction,level0_slowdown,level0_slowdown_with_compaction,memtable_compaction,memtable_slowdown,slowdown_for_pending_compaction_bytes,stop_for_pending_compaction_bytes,total_slowdown,total_stop,"
   }
  ]
 },
 "panels": [
  {
   "title": "cfstat actual $cfstats_actual",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "repeat": "cfstats_actual",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_actual\"}",
     "legendFormat": "L0"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_actual\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_actual\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_actual\"}",
     "legendFormat": "L3"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_actual\"}",
     "legendFormat": "L4"
    },
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_actual\"}",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstat rate $cfstats_rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "repeat": "cfstats_rate",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L0:$cfstats_rate\"}[1m])",
     "legendFormat": "L0"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L1:$cfstats_rate\"}[1m])",
     "legendFormat": "L1"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L2:$cfstats_rate\"}[1m])",
     "legendFormat": "L2"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L3:$cfstats_rate\"}[1m])",
     "legendFormat": "L3"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:L4:$cfstats_rate\"}[1m])",
     "legendFormat": "L4"
    },
    {
     "expr": "rate(engine:cfstats{job=$data_type, flag=\"compaction:Sum:$cfstats_rate\"}[1m])",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "cfstat io_stalls $io_stalls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
   "repeat": "io_stalls",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine:cfstats{job=$data_type, flag=\"io_stalls:$io_stalls\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  }
 ]
}