{
 "title": "ticker aggregate",
 "tags": [ "ticker" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric_name",
    "label": "metric_name",
    "query": "engine:bloom:filter:useful,engine:bloom:filter:full:positive,engine:bloom:filter:full:true:positive,engine:memtable:hit,engine:memtable:miss,engine:l0:hit,engine:l1:hit,engine:l2andup:hit,engine:compaction:key:drop:new,engine:compaction:key:drop:obsolete,engine:compaction:key:drop:range_del,engine:compaction:key:drop:user,engine:compaction:range_del:drop:obsolete,engine:compaction:optimized:del:drop:obsolete,engine:compaction:cancelled,engine:number:keys:written,engine:number:keys:read,engine:number:keys:updated,engine:bytes:read,engine:number:db:seek,engine:number:db:next,engine:number:db:prev,engine:number:db:seek:found,engine:number:db:next:found,engine:number:db:prev:found,engine:db:iter:bytes:read,engine:no:file:opens,engine:no:file:errors,engine:stall:micros,engine:db:cond:wait:nanos,engine:db:mutex:wait:nanos,engine:number:multiget:get,engine:number:multiget:keys:read,engine:number:multiget:bytes:read,engine:number:merge:failures,engine:bloom:filter:prefix:checked,engine:bloom:filter:prefix:useful,engine:number:reseeks:iteration,engine:getupdatessince:calls,engine:wal:synced,engine:compact:read:marked:bytes,engine:compact:read:periodic:bytes,engine:compact:read:ttl:bytes,engine:compact:write:marked:bytes,engine:compact:write:periodic:bytes,engine:compact:write:ttl:bytes,engine:number:direct:load:table:properties,engine:merge:operation:time:nanos,engine:filter:operation:time:nanos,engine:read:amp:estimate:useful:bytes,engine:read:amp:total:read:bytes,engine:number:rate_limiter:drains,engine:number:iter:skip,engine:number:multiget:keys:found,engine:num:iterator:created,engine:num:iterator:deleted,engine:files:marked:trash,engine:files:deleted:immediately,engine:error:handler:bg:errro:count,engine:error:handler:bg:io:errro:count,engine:error:handler:bg:retryable:io:errro:count,engine:error:handler:autoresume:count,engine:error:handler:autoresume:retry:total:count,engine:error:handler:autoresume:success:count,"
   }
  ]
 },
 "panels": [
  {
   "title": "write bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:bytes:written{job=\"stat\"}[1m])",
     "legendFormat": "bytes:written_cur"
    },
    {
     "expr": "rate(engine:bytes:written{job=\"stat\"}[$__range])",
     "legendFormat": "bytes:written_avg"
    },
    {
     "expr": "rate(engine:wal:bytes{job=\"stat\"}[1m])",
     "legendFormat": "engine:wal:bytes_cur"
    },
    {
     "expr": "rate(engine:wal:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "engine:wal:bytes_avg"
    },
    {
     "expr": "rate(engine:flush:write:bytes{job=\"stat\"}[1m])",
     "legendFormat": "flush:write:bytes_cur"
    },
    {
     "expr": "rate(engine:flush:write:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "flush:write:bytes_avg"
    }
   ]
  },
  {
   "title": "write batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:write:self{job=\"stat\"}[1m])",
     "legendFormat": "write:self_cur"
    },
    {
     "expr": "rate(engine:write:self{job=\"stat\"}[$__range])",
     "legendFormat": "write:self_avg"
    },
    {
     "expr": "rate(engine:write:other{job=\"stat\"}[1m])",
     "legendFormat": "write:other_cur"
    },
    {
     "expr": "rate(engine:write:other{job=\"stat\"}[$__range])",
     "legendFormat": "write:other_avg"
    },
    {
     "expr": "rate(engine:write:wal{job=\"stat\"}[1m])",
     "legendFormat": "write:wal_cur"
    },
    {
     "expr": "rate(engine:write:wal{job=\"stat\"}[$__range])",
     "legendFormat": "write:wal_avg"
    }
   ]
  },
  {
   "title": "compact write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:compact:write:bytes{job=\"stat\"}[1m])",
     "legendFormat": "lcompact:write:bytes:zip_cur"
    },
    {
     "expr": "rate(engine:compact:write:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "lcompact:write:bytes:zip_avg"
    },
    {
     "expr": "rate(engine:lcompact:write:bytes:raw{job=\"stat\"}[1m])",
     "legendFormat": "lcompact:write:bytes:raw_cur"
    },
    {
     "expr": "rate(engine:lcompact:write:bytes:raw{job=\"stat\"}[$__range])\t",
     "legendFormat": "lcompact:write:bytes:raw_avg"
    },
    {
     "expr": "rate(engine:remote:compact:write:bytes{job=\"stat\"}[1m])",
     "legendFormat": "dcompact:write:bytes:zip_cur"
    },
    {
     "expr": "rate(engine:remote:compact:write:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "dcompact:write:bytes:zip_avg"
    },
    {
     "expr": "rate(engine:dcompact:write:bytes:raw{job=\"stat\"}[1m])",
     "legendFormat": "dcompact:write:bytes:raw_cur"
    },
    {
     "expr": "rate(engine:dcompact:write:bytes:raw{job=\"stat\"}[$__range])\t",
     "legendFormat": "dcompact:write:bytes:raw_avg"
    }
   ]
  },
  {
   "title": "superversion",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:number:superversion_acquires{job=\"stat\"}[1m])",
     "legendFormat": "superversion_acquires_cur"
    },
    {
     "expr": "rate(engine:number:superversion_acquires{job=\"stat\"}[$__range])",
     "legendFormat": "superversion_acquires_avg"
    },
    {
     "expr": "rate(engine:number:superversion_cleanups{job=\"stat\"}[1m])",
     "legendFormat": "superversion_cleanups_cur"
    },
    {
     "expr": "rate(engine:number:superversion_cleanups{job=\"stat\"}[$__range])",
     "legendFormat": "superversion_cleanups_avg"
    },
    {
     "expr": "rate(engine:number:superversion_releases{job=\"stat\"}[1m])",
     "legendFormat": "superversion_releases_cur"
    },
    {
     "expr": "rate(engine:number:superversion_releases{job=\"stat\"}[$__range])",
     "legendFormat": "superversion_releases_avg"
    }
   ]
  },
  {
   "title": "compact read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:compact:read:bytes{job=\"stat\"}[1m])",
     "legendFormat": "lcompact:read:bytes:zip_cur"
    },
    {
     "expr": "rate(engine:compact:read:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "lcompact:read:bytes:zip_avg"
    },
    {
     "expr": "rate(engine:remote:compact:read:bytes{job=\"stat\"}[1m])",
     "legendFormat": "dcompact:read:bytes:zip_cur"
    },
    {
     "expr": "rate(engine:remote:compact:read:bytes{job=\"stat\"}[$__range])",
     "legendFormat": "dcompact:read:bytes:zip_avg"
    }
   ]
  },
  {
   "title": "memtable hit/miss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:memtable:hit{job=\"stat\"}[1m])",
     "legendFormat": "hit_cur"
    },
    {
     "expr": "rate(engine:memtable:hit{job=\"stat\"}[$__range])",
     "legendFormat": "hit_avg"
    },
    {
     "expr": "rate(engine:memtable:miss{job=\"stat\"}[1m])",
     "legendFormat": "miss_cur"
    },
    {
     "expr": "rate(engine:memtable:miss{job=\"stat\"}[$__range])",
     "legendFormat": "miss_avg"
    }
   ]
  },
  {
   "title": "number keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:number:keys:written{job=\"stat\"}[1m])",
     "legendFormat": "keys_written_cur"
    },
    {
     "expr": "rate(engine:number:keys:written{job=\"stat\"}[$__range])",
     "legendFormat": "keys_written_avg"
    },
    {
     "expr": "rate(engine:number:keys:read{job=\"stat\"}[1m])",
     "legendFormat": "keys_read_cur"
    },
    {
     "expr": "rate(engine:number:keys:read{job=\"stat\"}[$__range])",
     "legendFormat": "keys_read_avg"
    },
    {
     "expr": "rate(engine:number:multiget:keys:read{job=\"stat\"}[1m])",
     "legendFormat": "multiget_read_cur"
    },
    {
     "expr": "rate(engine:number:multiget:keys:read{job=\"stat\"}[$__range])",
     "legendFormat": "multiget_read_avg"
    }
   ]
  },
  {
   "title": "bytes read/writen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:bytes:written{job=\"stat\"}[1m])",
     "legendFormat": "bytes_written_cur"
    },
    {
     "expr": "rate(engine:bytes:written{job=\"stat\"}[$__range])",
     "legendFormat": "bytes_written_avg"
    },
    {
     "expr": "rate(engine:bytes:read{job=\"stat\"}[1m])",
     "legendFormat": "bytes_read_cur"
    },
    {
     "expr": "rate(engine:bytes:read{job=\"stat\"}[$__range])",
     "legendFormat": "bytes_read_avg"
    },
    {
     "expr": "rate(engine:number:multiget:bytes:read{job=\"stat\"}[1m])",
     "legendFormat": "multiget_read_cur"
    },
    {
     "expr": "rate(engine:number:multiget:bytes:read{job=\"stat\"}[$__range])",
     "legendFormat": "multiget_read_avg"
    }
   ]
  },
  {
   "title": "file",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine:no:file:opens{job=\"stat\"}[1m])",
     "legendFormat": "open_cur"
    },
    {
     "expr": "rate(engine:no:file:opens{job=\"stat\"}[$__range])",
     "legendFormat": "open_avg"
    },
    {
     "expr": "rate(engine:no:file:errors{job=\"stat\"}[1m])",
     "legendFormat": "error_cur"
    },
    {
     "expr": "rate(engine:no:file:errors{job=\"stat\"}[$__range])",
     "legendFormat": "error_avg"
    },
    {
     "expr": "rate(engine:files:marked:trash{job=\"stat\"}[1m])",
     "legendFormat": "trash_cur"
    },
    {
     "expr": "rate(engine:files:marked:trash{job=\"stat\"}[$__range])",
     "legendFormat": "trash_avg"
    },
    {
     "expr": "rate(engine:files:deleted:immediately{job=\"stat\"}[1m])",
     "legendFormat": "immediately_cur"
    },
    {
     "expr": "rate(engine:files:deleted:immediately{job=\"stat\"}[$__range])",
     "legendFormat": "immediately_avg"
    }
   ]
  },
  {
   "title": "$metric_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "repeat": "metric_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate($metric_name{job=\"stat\"}[1m])",
     "legendFormat": "rate"
    },
    {
     "expr": "rate($metric_name{job=\"stat\"}[$__range])",
     "legendFormat": "window_avg"
    }
   ]
  }
 ]
}